Description: >
    Buchi / Udacity
    This template deploys a VPC
Resources:
    TestVPC:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: 10.0.0.0/16
            EnableDnsHostnames: True